### ISSUE TITLE
Create a "How to contribute recipe" recipe 

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#10]
**Is your feature request related to a problem? Please describe.**
I want to contribute content but need guidance ? Is there a template ? 

**Describe the solution you'd like**

**Describe alternatives you've considered**
current template is ok but possible too shallow and lacks guidance.

**Additional context**
Request made following FAIRplus face 2 face meeting January 2020 at the Wellcome Trust Genome campus. @JolandaS @tburdett @nsjuty as per our discussion.

**Comment by robertgiessmann** [comment]
@proccaserra is this done?
