### ISSUE TITLE
Create Data Catalogue Recipe

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#11]
# Recipe1: Anonymizing Patient Data

**identifier:**

**authors:**
Wei Gu
Venkata Satagopam
Philippe Rocca-Serra

**maintainers:**

**version:**

**license**

## Ingredients:

    1. Identifier Schema:
        - DOI
        - ARK

    2. Metadata Model:
        - DATS
        - DCAT 1.0
        - DCAT 2.0
        - ISA

    3. Vocabularies and Terminologies:
        - EFO
        - OBI
        
    4. Data Format:
        - JSON
        - JSON-LD

    5. Tools and Software:
        - GRAPHQL
        
## Objectives:

Findability

Allow dataset discovery

### Step2:
     
     ### Step3:
     
     ### Step4:
     
     ### Step5: ...

**Comment by AlasdairGray** [comment]
Is it worth having a simple first step of adding in schema.org markup?

**Comment by daniwelter** [comment]
Full first draft now available and in PR https://github.com/FAIRplus/the-fair-cookbook/pull/66

**Comment by robertgiessmann** [comment]
closed because duplicating #66
