### ISSUE TITLE
Create content/recipe on the theme "What are the FAIR principles"?

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#117]
## Main Objectives

The main purpose of this recipe is:

to provide context and background information to lead into:
- [x]  'IMI and Data Management' recipe
- [x]  'FAIR in the context of IMI' recipe

**Comment by daniwelter** [comment]
Fixed in commit c189e4048d2357abc693ae7ce2a8704ff211b2b9
