### ISSUE TITLE
Objective needs updating

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#128]
The objective for the [How to create a recipe with git](https://fairplus.github.io/cookbook-dev/recipes/help/how-to-create-recipe-with-git.html) recipe states

> Learn how to get set up to commit to the FAIR Cookbook or create a recipe using the GoogleDoc Template

Surely this should talk about using Git and markdown files/HackMD

**Comment by robertgiessmann** [comment]
fixed in 2b97348
