### ISSUE TITLE
Cookbook-dev points to a wrong offical cookbook link?

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#129]
Hi, 

I assume https://fairplus.github.io/the-fair-cookbook/intro is the official cookbook.  

However, cookbook-dev directs me to the https://the-fair-cookbook.netlify.app/intro. This netlify page is slightly different with the official cookbook. Not sure if this is designed on purpose, or it's just a small mistake.

![1](https://user-images.githubusercontent.com/54043294/93435240-084f1b00-f8c1-11ea-840e-7469f35e0c8d.png)

**Comment by robertgiessmann** [comment]
Hi @proccaserra , I can confirm: when I open https://fairplus.github.io/the-fair-cookbook it redirects me to https://fairplus.github.io/cookbook-dev/intro -- is that intended behavior? If not, let me know, I can fix it.

**Comment by proccaserra** [comment]
@robertgiessmann. Good for now, thx for doing the redirect. this is just as good.
