### ISSUE TITLE
Recipe request: recipes about provenance

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#130]
Hi, 

I'd like to request more provenance-related recipes in the cookbook. Topics I am interested in are:

- What is provenance.
- Culture change, incentives for provenance tracking.
- For different data types, what is the best provenance model?
- how to build a sustainable provenance tracking system/service?
- data provenance tools
- Provenance tracking best practice.

There might be other questions that can be answered in the cookbook.

Cheers,
Fuqi

**Comment by proccaserra** [comment]
https://w3id.org/faircookbook/FCB036
