### ISSUE TITLE
Recipe on Licensing

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#131]
Start from ATI document
Augment on the issue of the data licensing

- [ ] label this issue with the corresponding Use Case Number (at your right side: click "Labels" -> "UC..."
- [x] identify author  -  Philippe
- [ ] agree with editors on scope
- [ ] write abstract
- [ ] write feedback on abstract
- [ ] make corresponding changes to abstract
- [ ] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe

**Comment by JolandaS** [comment]
@proccaserra is it okay with you if we changed the description for this issue to include the recipe track list setup?

**Comment by JolandaS** [comment]
@proccaserra any updates on this recipe? Is it correct that you are the author now?

**Comment by proccaserra** [comment]
Decision to point/reuse content from The Turing Way Book which cover 
- General introduction on Licensing
- Licenses for software
- Licenses for data
All 3 recipes are pulled from ATI content, and an `attribution note` is added to each of them to ensure readers are aware of the original creation.
This was discussed and agreed with ATI TWB developers who asked for our DOI to use a similar convention should they use our content.

**Comment by JolandaS** [comment]
@proccaserra Could you add a link to the actual recipes?

**Comment by proccaserra** [comment]
Hi @JolandaS, here:

- [x] https://fairplus.github.io/the-fair-cookbook/content/recipes/reusability/ATI-licensing.html
- [x] https://fairplus.github.io/the-fair-cookbook/content/recipes/reusability/ATI_licensing_software.html
- [x ] https://fairplus.github.io/the-fair-cookbook/content/recipes/reusability/ATI_licensing_data.html

(note: yes, I am aware of rendering issues)

**Comment by daniwelter** [comment]
Fixed in commit c189e4048d2357abc693ae7ce2a8704ff211b2b9
