### ISSUE TITLE
the cookbook official site is down

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#141]
Hi, 

I am trying to access the cookbook official site. https://fairplus.github.io/the-fair-cookbook/intro And got a 404 error. See screenshot below.

![Movavi ScreenShot 148 - Page not found · GitHub Pages - fairplus github io](https://user-images.githubusercontent.com/54043294/96650156-40b3a000-132a-11eb-98af-3c4742abe926.jpg)

Could you please look into it? Thanks!

Fuqi

**Comment by proccaserra** [comment]
works for me, on all browsers.
it could be a blip last night

**Comment by FuqiX** [comment]
Hi, @proccaserra 

I asked another colleguege to test it.

It seems this URL, with __/intro__,  https://fairplus.github.io/the-fair-cookbook/intro returns 404. 
This URL, without __/intro__ , https://fairplus.github.io/the-fair-cookbook is redirected to the cookbook-dev site 

URLs, like https://fairplus.github.io/the-fair-cookbook/recipes/fair-data-matrix-recipe.html,  also returns 404.

It seems the links are redirected to cookbook-dev. The links to all individual recipes in the official site don't work.
