### ISSUE TITLE
Referencing style

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#143]
Do we have a consistent style for providing references?

In using [Minting Identifiers recipe](https://fairplus.github.io/cookbook-dev/recipes/findability/identifiers.html) as a template for the IMS recipe I noticed that the references are not consistent in the style or content. For example reference 11 does not include the authors while reference 12 does.

**Comment by daniwelter** [comment]
Fixed in commit c189e4048d2357abc693ae7ce2a8704ff211b2b9
