### ISSUE TITLE
Failed to run ThebeLab code in the HTML page

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#15]
**Describe the bug**
Unable to run the code provided on the HTML page. Running the code got stuck on `waiting for kernel...`.

**To Reproduce**
1. Go to any recipe, e.g. https://fairplus.github.io/the-fair-cookbook/recipes/fair-data-matrix/0-rose-metabolites-Python-data-handling.html
2. Click on the code cell ->  `interactive mode`  - > `run`

3. Running the code got stuck on `"waiting for kernel"`

**Additional context**
- I am able to run [ThebeLab example code](https://thebelab.readthedocs.io/en/latest/), though it also took some time to connect to the kernel.
- Downloading the .ipynb file and running locally it work for me.

**Screenshot**
The code got stuck on `Waiting for kernel`
![thebelab](https://user-images.githubusercontent.com/54043294/74842508-71b67d80-5322-11ea-8353-f267f4226616.png)

**Comment by proccaserra** [comment]
Deactivating that feature, and testing with binder instead (which does not work either). closing for now
