### ISSUE TITLE
migrating away from jupyter-book legacy

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#161]
target version: jupyter-book 0.9.1
- [x] configure and install jb
- [x] update all recipes
- [x ] create toc.yml 
- [x] deploy test set- up -> [https://proccaserra.github.io/the-fair-cookbook-ng/content/home.html](https://proccaserra.github.io/the-fair-cookbook-ng/content/home.html)

- [ ] fine-tune CSS for rendering of table
- [x] align with ATI Turing Way Book styling guideline and build process
- [ ] flick the switch to the main site

**Comment by daniwelter** [comment]
Fixed in commit c189e4048d2357abc693ae7ce2a8704ff211b2b9
