### ISSUE TITLE
All links on the Introduction-page (data management plan etc.) refer back to the same page

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#164]
https://fairplus.github.io/the-fair-cookbook/content/recipes/introduction/FAIR-cookbook-audience.html

Note: 
a number of links are placeholders for recipes under development.

Linkage will happen when the new content is delivered and incorporated

**Comment by robertgiessmann** [comment]
outdated, not a bug anymore.
