### ISSUE TITLE
investigate, test and define recipe for conversion from gdoc markdown

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#20]
**Is your feature request related to a problem? Please describe.**
some people find markdown & github too challenging and want to write in gdoc (collaborative editing). investigation how to convert from gdoc to markdown

- [ ]  https://github.com/supreetpal/gdoc-markdown-converter

- [ ]  https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
conversion should match the github faircookbook recipe template
https://fairplus.github.io/the-fair-cookbook/recipes/recipe-template.html

**Comment by daniwelter** [comment]
Fixed in commit c189e4048d2357abc693ae7ce2a8704ff211b2b9
