### ISSUE TITLE
Provide an easier way to edit Markdown -> investigate HackMD.io

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#21]
**Is your feature request related to a problem? Please describe.**
people with no experience with github and markdown feel the learning curve is too steep
googledoc provides nice collaborative editing, low barrier to entry but Markdown export not available and conversion tool are wanting.

**Describe the solution you'd like**
allows push and pull to github
allows use of template
allows collaborative editing
allows comments in a markdown document
allows view of markdown *and* rendered version
allows multi users.

https://hackmd.io/c/tutorials/%2Fs%2Finvite

**Comment by proccaserra** [comment]
testing done today, need more miles to understand gotchas
reach out to https://github.com/alan-turing-institute/the-turing-way and https://github.com/alan-turing-institute/the-turing-way#question-KirstieJane

**Comment by robertgiessmann** [comment]
think we can close this successful now. Looking forward to using this tool at the face-to-face!
