### ISSUE TITLE
Review the Cookbook CMMI section

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#22]
**Is your feature request related to a problem? Please describe.**

Suggestion by Oya Beyan to possibly move it earlier to highlight how the CMMI model can be used to define a FAIRification process in terms of goals to achieve for a given set of capabilities

**Comment by robertgiessmann** [comment]
@proccaserra This might have become stale in the meantime; can issue be closed?

**Comment by proccaserra** [comment]
Hi @robertgiessmann,  we should live it open so we can log the experience we'll be running next week @oyadenizbeyan and Ibrahim iemam.
The idea was to have them to go over a couple of recipes to review and reform based on the current version of the CMMI model

**Comment by oyadenizbeyan** [comment]
I updated the template and created a pull request

**Comment by proccaserra** [comment]
see #438 
see #444
