### ISSUE TITLE
Migration of tickets/issues between github repositories

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#24]
investigate if there are easy options available in github to transfer recipe related tickets created in the squad repositories to the FAIR cookbook gh repo

**Comment by proccaserra** [comment]
[https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository)
@nsjuty @JolandaS

**Comment by robertgiessmann** [comment]
@proccaserra  done?

**Comment by proccaserra** [comment]
@robertgiessmann squad leads opted for leaving current issues for this round (i.e. until end of the week). 
All new recipe issues will be filed in the FAIR+ cookbook repo.
Let's leave it open until the end of the virtual F2F meeting and act on Friday. Cheers!

**Comment by daniwelter** [comment]
Fixed in commit c189e4048d2357abc693ae7ce2a8704ff211b2b9
