### ISSUE TITLE
Next/Previous recipe links on section pages

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#282]
Previous recipe link on [Interoperability page](https://fairplus.github.io/the-fair-cookbook/content/recipes/interoperability.html) not as expected. I would not expect to end up at the last of the accessibility recipes. I would expect a link to the Accessibility section.

![Screen Shot 2021-05-17 at 11 07 50](https://user-images.githubusercontent.com/1141265/118471885-2430e800-b700-11eb-97e8-1000a42ef372.png)
Your issue content here.

**Comment by robertgiessmann** [comment]
agreed that it is counter-intuitive, but it needs to be tackled from jupyter-book -- the next/previous are auto-generated. putting it low-prio because of the high hurdle, thus... sorry. :(

**Comment by AlasdairGray** [comment]
No problem.

Also need to think about the numbers as they don't include the section number, i.e. there are multiple recipes that have the designation 1. rather than there being a 1.1, 2.1, 3.1, etc.

**Comment by proccaserra** [comment]
@AlasdairGray this is a known issue in jupyter-book: https://github.com/executablebooks/jupyter-book/issues/1268

and possibly this  https://jupyterbook.org/customize/toc.html#how-headers-and-sections-map-onto-to-book-structure

thx for reporting (we knew about it)
