### ISSUE TITLE
Orange arrow at top of recipes

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#284]
Not obvious what this arrow does; hover over takes a long time to come on.
![Screen Shot 2021-05-17 at 11 17 15](https://user-images.githubusercontent.com/1141265/118473181-99e98380-b701-11eb-90e0-434bb3af4c60.png)

**Comment by robertgiessmann** [comment]
interesting... the arrow hops on my computer from very left to middle when you change the width of the browser window. I'll prioritize this as low-prio though, alright?

**Comment by proccaserra** [comment]
now fixed by @terazus in the new set-up
