### ISSUE TITLE
Phrasing of hyperlinks to other recipes that use the title of the recipe

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#285]
On the [BridgeDb recipe](https://fairplus.github.io/the-fair-cookbook/content/recipes/interoperability/bridgedb-recipe.html) there is the following text

> [Interlink data from different sources](https://fairplus.github.io/the-fair-cookbook/content/recipes/interoperability/identifier-mapping.html#fcb-interop-idmapping) is an essential step for data reusability and interoperability.

A more natural phrasing would be
> [Interlinking data from different sources](https://fairplus.github.io/the-fair-cookbook/content/recipes/interoperability/identifier-mapping.html#fcb-interop-idmapping) is an essential step for data reusability and interoperability.

However, the text for the link is coming from the title of the recipe so not sure what to do in this case.

**Comment by AlasdairGray** [comment]
Again later in the recipe

> Despite the lack of a dedicated BridgeDb Python library, we show here how to use the BridgeDb Webservices to perform the mappings suggested under [Cases](https://fairplus.github.io/the-fair-cookbook/content/recipes/interoperability/bridgedb-recipe.html#Cases)

I'm not sure what the correct text should be here.

**Comment by robertgiessmann** [comment]
Hi @AlasdairGray , thanks for the comments. I assume the underlying question is how to create references with a custom text, although using the {ref} directive? 

There is a short bit in the jupyter-book documentation, but not put very explicitly: https://jupyterbook.org/content/references.html 

I need to try for myself (and will) but I guess that 

{ref}`Custom text for a reference <fcb-label-of-the-reference>`

is what we are looking for.

**Comment by robertgiessmann** [comment]
fixed in 5694edd86985f087ec87b4c5b7d0268006aabe99
