### ISSUE TITLE
Styling of level 4 headings

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#287]
There appears to be no styling for level 4 headings `#### heading`. These are used in the BridgeDb recipe.

**Comment by robertgiessmann** [comment]
introduced one. Hope you like it? @terazus , fine for you? See for rendered version here: 
https://fairplus.github.io/the-fair-cookbook/content/recipes/interoperability/bridgedb-recipe.html

**Comment by terazus** [comment]
Code and output looks fine to me :)

**Comment by robertgiessmann** [comment]
Cool, will close then. :)
