### ISSUE TITLE
Broken citation in BridgeDb recipe

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#288]
Link to Batchelor et al paper is not working

![Screen Shot 2021-05-17 at 12 05 16](https://user-images.githubusercontent.com/1141265/118478804-344cc580-b708-11eb-8c96-2a28106859b2.png)

Code is
```
 {cite}`batchelor_scientific_nodate`
```

**Comment by robertgiessmann** [comment]
fixed in 035cc46a159446ffc6d2f2dcbe175da0b99e4078
