### ISSUE TITLE
Broken link to BridgeDb code

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#289]
The following link in the BridgeDb recipe that is meant to take you to the working code does not work; I got a 404 error.

https://github.com/FAIRplus/the-fair-cookbook/tree/bridgedb/docs/content/recipes/interoperability/bridgedb
![Screen Shot 2021-05-17 at 12 10 47](https://user-images.githubusercontent.com/1141265/118479456-f0a68b80-b708-11eb-856b-caf2f299a5d2.png)

**Comment by robertgiessmann** [comment]
fixed in 460835b
