### ISSUE TITLE
aspera recipe: improve the flowchart 

### ISSUE THREAD

**Issue by Philip-Gribbon** [FAIRplus/the-fair-cookbook#298]
Section 2.2

The shapes of some flowchart boxes seem a bit random when compared to standards for data / operations  etc? Doesn't seem to match the intention of the text
https://en.wikipedia.org/wiki/Flowchart

**Comment by robertgiessmann** [comment]
hi @Philip-Gribbon , how would you design the shapes? The diamonds look good for me , I see that rounded and rectangle boxes are mixed in there. I'm not a pro on flowcharts, though... :/

**Comment by proccaserra** [comment]
@robertgiessmann the round box should indicate 'final' so @Philip-Gribbon is correct but the purpose was to produce a diagram/overview, not necessarily a fully standard compliant flow-chart. no time to fix now, maybe next rounds of edits

**Comment by robertgiessmann** [comment]
fixed in f6c0544

**Comment by robertgiessmann** [comment]
@Philip-Gribbon , happy if you have a look. :) https://fairplus.github.io/the-fair-cookbook/content/recipes/accessibility/aspera.html

**Comment by Philip-Gribbon** [comment]
Hi Robert,

Changes all look good. To me it seems a lot clearer overall

Best

Phil
