### ISSUE TITLE
Discontinuous enumeration on /content/recipes/findability/seo/bioschemas-data-page.html

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#326]
The steps in the method section keep resetting to 1 after an image is included. The screenshot shows step 3.
![Screen Shot 2021-05-26 at 10 29 44](https://user-images.githubusercontent.com/1141265/119637200-5384da80-be0d-11eb-9f13-2e4fdd5a3efd.png)

Not sure if this affects other pages.

**Comment by proccaserra** [comment]
![image](https://user-images.githubusercontent.com/517736/181440942-a4432c47-56bc-4afc-88f1-4cf1a2d34013.png)
