### ISSUE TITLE
w3id fcb identifiers causing a 404

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#339]
FCB019:
https://fairplus.github.io/the-fair-cookbook/content/recipes/interoperability/ontology-why-using-them.html
changed to 
https://fairplus.github.io/the-fair-cookbook/content/recipes/interoperability/introduction-terminologies-ontologies.html
without updating the .htaccess file

similar issue with:
FCB025:
https://fairplus.github.io/the-fair-cookbook/content/recipes/interoperability/creating_data_dictionary.html
changed to
https://fairplus.github.io/the-fair-cookbook/content/recipes/interoperability/creating-data-dictionary.html

shortly sending a PR for the .htaccess file to address this

**Comment by robertgiessmann** [comment]
created a PR: https://github.com/perma-id/w3id.org/pull/2213

**Comment by robertgiessmann** [comment]
fixed on 9th of June; closing now.
