### ISSUE TITLE
invite recipe: sth about identifiers.org

### ISSUE THREAD

**Issue by robertgiessmann** [FAIRplus/the-fair-cookbook#34]
Hi @nsjuty ,

I hope I don't find you too stressed out (I bet on the "stressed out", though...) .

I would like to invite you to submit an 100-150 word abstract regarding a contribution on identifiers.org . It would be great if you have a look at the ToC draft (https://docs.google.com/spreadsheets/d/13B2aLm5ZXFUwAu6DlcL7soWL8yzX6juR4ijgUpzIsv4/edit#gid=818333385), to find out where a recipe of yours might fit best.

Can you confirm a deadline to submit this abstract until Friday 2020-04-24 (or make an alternative suggestion)?

Thank you so much in advance!
    Robert

**Comment by robertgiessmann** [comment]
Nick personally said he is going to try write something till end of the week.

/Remind me on Friday

**Comment by nsjuty** [comment]
identifiers.org as a service would fit into:

2.3.2: Reference
(It would fit in, or be referenced from, subsections under 'lists of standards...' )

3.1.3, esp 3.1.3.1 (definitions) and 3.1.3.4 (existing infrastructure)

3.3.1.2 (syntactic interoperability standards)


Abstract

Identifiers.org is a resource provided through EMBL-EBI, as part of the 'Interoperability' Platform, and is an ELIXIR recommended interoperability resource (https://elixir-europe.org/platforms/interoperability/rirs).

This resource provides 2 key pieces of functionality:

a. It provides a simple redirection mechanism, as with any resolver, but additionally is able to identify data records in both a location-dependent, and location-independent manner. This allows one to identifify specific records, which may be located in multiple different resources, unambiguously, while also allowing references to instance specific record hosting. This relies upon a curated 'registry' of 'data collection prefixes' and 'provider codes'.

b. It is a 'meta-resolver', able to resolve numerous prefix form (also known as CURIEs) identifers commonly encountered primarily in the Life Scince domain. This functionality is backed up through a collaborative agreement with the US-based 'meta-resolver' n2t.net, where these resources share submissions through a data exchange mechanism that is executed daily.

**Comment by nsjuty** [comment]
@robertgiessmann @AlasdairGray 
I've put the abstract here, as I was not entirely sure where you wanted it. Its just plain text for now, so I hope thats ok.
