### ISSUE TITLE
Add "Related Recipes" section in individual recipe page

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#35]
When I browse a recipe in the Cookbook website, I want to find all recipes related to the current recipe, so that I can be easily directed to other recipes and better decide which recipe to read first.

**Example:**
[Recipe 1.3](https://github.com/FAIRplus/FAIRPlus_squad1/issues/3) is dependent on [Recipe 1.2](https://github.com/FAIRplus/FAIRPlus_squad1/issues/2)
[Recipe 1.3](https://github.com/FAIRplus/FAIRPlus_squad1/issues/3) is related to [Recipe 1.1](https://github.com/FAIRplus/FAIRPlus_squad1/issues/1) and [Recipe 3.1]

**Possible solutions**
1. Add a "related recipe" side panel in the recipe page. This might takes some work
2. Add a "related recipe" section in the recipe template. So that authors can link the recipes manually using hyperlinks.

One problem I had linking recipes manually is that some recipe links are not available yet. 
Can we 'pre-register' the recipe, so that other recipes can point to the unfinished recipe? Or is it the editors' job to link the recipes manually?

**Comment by ereynrs** [comment]
This issue could be linked to the discussion about recipe coverage, tracking and overlaping (@nsjuty @proccaserra at [2020-06-03](https://docs.google.com/document/d/1l8ibG9U4EOKHSJ0fRGqVZhqPGEO-AnkO-2giN8J81ds/edit#heading=h.oyvvicqve630))

Development of a use case diagram (toy example [here](https://docs.google.com/document/d/1l8ibG9U4EOKHSJ0fRGqVZhqPGEO-AnkO-2giN8J81ds/edit#heading=h.oyvvicqve630)) could help?

**Comment by proccaserra** [comment]
now all recipes have a section "what to read next' with links to internal and external resources to the book.
