### ISSUE TITLE
Who is original author of content/recipes/findability/seo.md?

### ISSUE THREAD

**Issue by robertgiessmann** [FAIRplus/the-fair-cookbook#358]
Hi @AlasdairGray , 

maybe you can already help: in https://github.com/FAIRplus/the-fair-cookbook/tree/migrating/content/recipes/findability/seo.md, it says that you, philippe and leyla all did review & editing, but noone the original draft. Could you clarify / correct? Thanks in advance!

**Comment by AlasdairGray** [comment]
Philippe wrote the first draft of [FCB010](https://fairplus.github.io/the-fair-cookbook/content/recipes/findability/seo.html), I then revised and extended it.

Leyla performed a final review in which she did some minor modifications.

**Comment by robertgiessmann** [comment]
Thanks @AlasdairGray . I distilled your information to this authors block:

Philippe: Writing - Original Draft, Conceptualization
Alasdair: Writing - Original Draft, Writing - Review & Editing
Leyla: Writing - Review & Editing


Is that okay?

**Comment by robertgiessmann** [comment]
https://github.com/FAIRplus/the-fair-cookbook/pull/364
