### ISSUE TITLE
Add dependency/requirements section in the recipe template

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#36]
As @ereynrs suggested in R1.3, "the assumption of the recipe be explicitly stated among a ingredients/dependencies/requirements section. "

When reading a recipe, I want to know what are the requirements to understand and test it, so that I can decide whether to continue with the recipe or not.

The requirements can be 
- technical requirements (Bash knowledge needed)
- recipe dependency (read Recipe 1 before Recipe 2)
- knowledge requirement (OBO foundry knowledge needed)
- ...

Shall we create a new Requirements section in the recipe template? Or shall we provide such info in the Ingredients section?

**Comment by robertgiessmann** [comment]
Sounds fine to me. @FuqiX , can you make a proposal for this directly in the recipe template: https://github.com/FAIRplus/the-fair-cookbook/blob/master/docs/content/recipes/recipe-template.md ?

@proccaserra , what do you think?

**Comment by robertgiessmann** [comment]
/close 

closed by commit ced6232

**Comment by robertgiessmann** [comment]
this should be tackled also in an automated fashion. I did not find any improvement on the recipe template yet.
