### ISSUE TITLE
New recipe: Overview of factors essentially required for project prioritization in a FAIRification task

### ISSUE THREAD

**Issue by YojanaGadiya** [FAIRplus/the-fair-cookbook#377]
If you needed to add a task to the list below, please think about amending the issue template: https://github.com/FAIRplus/the-fair-cookbook/blob/migrating/.github/ISSUE_TEMPLATE/meta-checklist.md
Great! Now, to the actual tasks:

- [x] identify author
- [x] write abstract
- [x] agree with editors on abstract
- [x] write recipe
- [x] identify reviewer
- [x] conduct review
- [x] incorporate reviewer's comments
- [x] publish recipe

**Comment by YojanaGadiya** [comment]
The main purpose of this recipe is:
to provide an overview of pointers that could help users in prioritisation and selection of potential projects, processes, or data for FAIRification. We also highlight the reasons for making the data FAIR. Furthermore, for each of the pointers, we provide comparative benefits between different stages and justify the order of the stages required for FAIRification.

**Comment by YojanaGadiya** [comment]
@robertgiessmann and @proccaserra any idea on which domain this recipe would fit within the FAIR principles?

**Comment by robertgiessmann** [comment]
hi @YojanaGadiya , guess this is more meta level, foundational stuff. 

Regarding the abstract: could you put some concrete content in, or do you still work on that? I personally find that the "the main purpose of this recipe is" sentence gives me a writer's block; I like to think of it more of a typical academic paper abstract with ~200 words.

**Comment by YojanaGadiya** [comment]
@robertgiessmann please find the abstract below:
With the increased awareness in the FAIR principles, the drive to implement them can be felt in projects and programs. However, considering the volume and variety of such projects and the finite nature of available resources, it is also necessary to establish a principle approach to prioritizing project or data FAIRification. The present recipe aims to provide insights into how to go about this by outlining essential elements which have been considered and “battle tested”.  

In the recipe, we would begin by pointing out the reasons why one needs to make their dataset FAIR. Following this, a brief overview of the dataset corpus formulation. Once the team has collected all the necessary data, it can now pass through the prioritisation phase. Here a thorough assessment of the dataset based on certain criteria is done. This assessment in turn leads to development of a scorecard. Finally, with the points each dataset has achieved in the scorecard, raking can be established and projects or datasets can be prioritized

**Comment by robertgiessmann** [comment]
we skipped the review phase here for staying in sync with a separate publication; this still needs to be done.

**Comment by robertgiessmann** [comment]
@YojanaGadiya @proccaserra : do we have naturally qualified reviewers for this? Phil Gribbon, or David, maybe?

**Comment by proccaserra** [comment]
@robertgiessmann I believe they both provided input when shaping the content. It might be good to have someone like @weiguUL  and @vioannid to over it too.

**Comment by weiguUL** [comment]
@proccaserra I have been involved in reviewing draft before pushing to github. Maybe we ask someone not on the list.

**Comment by YojanaGadiya** [comment]
With an internal discussion with Phil, Wei, and Vassilios, we identified the following members as potential reviews :
1. Nick Juty (@nsjuty)
2. Danielle Welter (@daniwelter)
3. Vassilios (@vioannid )

**Comment by proccaserra** [comment]
@YojanaGadiya I'll assign them to do the review.

**Comment by robertgiessmann** [comment]
marked as "approved" after review
