### ISSUE TITLE
Review of recipe: Overview of factors essentially required for project prioritization in a FAIRification task

### ISSUE THREAD

**Issue by YojanaGadiya** [FAIRplus/the-fair-cookbook#386]
If you needed to add a task to the list below, please think about amending the issue template: https://github.com/FAIRplus/the-fair-cookbook/blob/migrating/.github/ISSUE_TEMPLATE/meta-checklist.md
Great! Now, to the actual tasks:

- [x] identify author
- [ ] write abstract
- [x] agree with editors on abstract
- [x] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [x] publish recipe

#377 recipe had bypassed the review phase earlier for publication purposes.

**Comment by robertgiessmann** [comment]
I will reopen #377 to keep it in one place. Thanks for giving us the heads-up that there is still work to be done! :)
