### ISSUE TITLE
"How to cite" can be improved

### ISSUE THREAD

**Issue by egonw** [FAIRplus/the-fair-cookbook#388]
The [section](https://fairplus.github.io/the-fair-cookbook/content/home.html#how-to-cite-it) now looks like this:

![image](https://user-images.githubusercontent.com/26721/151172725-5ff513cf-1682-4a87-826c-702e2a9f3fd9.png)

The Deliverable is mentioned but without DOI and/or URL (to metadata), but also there is no information about how to cite this Cookbook itself, or link to BibTeX, or DOI for archived versions on Zenodo (e.g. half yearly releases).

**Comment by robertgiessmann** [comment]
True. This should be improved. Maybe a good breakout room for a bookdash? @proccaserra ?
