### ISSUE TITLE
new recipe did not get a unique identifier yet

### ISSUE THREAD

**Issue by egonw** [FAIRplus/the-fair-cookbook#417]
![image](https://user-images.githubusercontent.com/26721/160816864-4bc25b2b-b708-4246-b456-fa8ba729b20f.png)

@proccaserra, what is the process here?

**Comment by proccaserra** [comment]
Hi @egonw I'll take care of this one. I have already prepared the PR to w3id as I am batching the minting.

**Comment by proccaserra** [comment]
https://w3id.org/faircookbook/FCB060
