### ISSUE TITLE
check JSON-LD for the recipes

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#418]
as per:
https://twitter.com/kidehen/status/1509134366118752259/photo/1

**Comment by proccaserra** [comment]
see also #419

- [ ] check possible conflict in code

https://github.com/FAIRplus/the-fair-cookbook/blob/migrating/_ext/panels_fairplus.py#L223
@robertgiessmann 

- [ ] check also metadata default setting in jupyterbook

**Comment by robertgiessmann** [comment]
could you contact kidehen about the actual question / problem? it's not immediately clear to me what we would need to fix... The json-ld was programmed by Dominique in https://github.com/FAIRplus/the-fair-cookbook/commit/eda6ea5ec5e5268a52a0560631c275b53dce0bae ; I didn't go into the details of how to use it, but that's probably documented somewhat on schema.org or so. I believe the howto class in schema.org is more aimed at "how to fix your sink", though, so maybe indeed not fully applicable. But I believe I actually didn't get the question / problem.

**Comment by proccaserra** [comment]
I initially thought kidehen report was about a json-ld payload was found in the body, not the head but the google Rich result tools does find the information in our pages. 
It complains about something else:

![image](https://user-images.githubusercontent.com/517736/160996625-ac570349-299a-4c89-b834-cf8e018d4e33.png)

the pb is a missing element, which may also indicate a change in required element on the type with the recent releases of sdo.
If Dominique did the work, I am pretty sure he checked against the google tool.

Agree with @rgiessmann , reporting an issue is better made via github issue tracker 

Thx both.

**Comment by AlasdairGray** [comment]
You would be better checking with the Schema.org validator since it works with types that Google does not have applications using. You can find it at https://validator.schema.org/

In Bioschemas we use it extensively and pass URLs automatically to is, e.g. FAIRsharing https://validator.schema.org/#url=https://fairsharing.org/

**Comment by AlasdairGray** [comment]
Hmm, seems that FAIRsharing no longer works. Here is another example
https://validator.schema.org/#url=https%3A%2F%2Fdisprot.org%2FDP00086

**Comment by AlasdairGray** [comment]
The schema.org validator is the old Google Structured Data Testing Tool with the Google specific profiles removed. It is still hosted on Google servers and respects robots.txt files.

The Rich Snippets tool is targeted specifically to support their applications. 

I find that the Schema.org validator give a more direct mechanism to get to the information that we are interested and a nicer view.
