### ISSUE TITLE
Generating InChIKeys for IUPAC names

### ISSUE THREAD

**Issue by egonw** [FAIRplus/the-fair-cookbook#425]
Great! Now, to the actual tasks:

- [x] identify author
- [x] write abstract
- [x] agree with editors on abstract
- [x] write recipe
- [x] identify reviewer
- [x] conduct review
- [x] incorporate reviewer's comments
- [x] publish recipe

**Comment by egonw** [comment]
= Why this recipe?

It is a step in the larger work described in https://github.com/FAIRplus/the-fair-cookbook/issues/396

= Author

Egon

= Abstract

IUPAC names describe chemical structures, but one chemical compound can have multiple (equivalent) IUPAC names. That makes IUPAC names unsuited as global unique identifier. The InChIKey addresses this issue. This recipe describes how cheminformatics can be used to translate IUPAC names into unique InChIKeys.

**Comment by egonw** [comment]
Preview: https://egonw.github.io/cookbook-dev/content/recipes/infrastructure/iupac-names.html

**Comment by robertgiessmann** [comment]
Hi @egonw , I like it! One thing, though: InChI-Keys are not unique, either, are they? There is at least the theoretical chance of key collision. But if that is pointed out as a caveat, I am more than happy! :)

**Comment by YojanaGadiya** [comment]
Maybe this might help in getting some content or directing the readers to this resource - http://inchi.info/inchikey_overview_en.html. It would be good to highlight that differences I think.

**Comment by egonw** [comment]
```groovy
@Grab(group='io.github.egonw.bacting', module='managers-inchi', version='0.0.42')
@Grab(group='io.github.egonw.bacting', module='managers-opsin', version='0.0.42')
@Grab(group='org.apache.logging.log4j', module='log4j-api', version='2.18.0')
@Grab(group='org.apache.logging.log4j', module='log4j-core', version='2.18.0')

workspaceRoot = "../ws"
opsin = new net.bioclipse.managers.OpsinManager(workspaceRoot);
inchi = new net.bioclipse.managers.InChIManager(workspaceRoot);

anInChI = inchi.generate(
  opsin.parseIUPACName("methane")
)
println "InChI: " + anInChI.value
println "InchIKey: " + anInChI.key
```

**Comment by egonw** [comment]
Or in Python:

![image](https://user-images.githubusercontent.com/26721/178197918-ef59fc26-f608-441a-a117-2cb644c34bc3.png)

**Comment by proccaserra** [comment]
@egonw @robertgiessmann @YojanaGadiya @tabbassidaloii 

how far from PR? 

Would you mind setting a milestone to this content and the associated isses (#396) ?

**Comment by egonw** [comment]
before the end of August.

**Comment by egonw** [comment]
My summer did not go as planned. But making the PR now.

**Comment by egonw** [comment]
Published: https://w3id.org/faircookbook/FCB080
