### ISSUE TITLE
Missing persistent id in some recipes

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#428]
Hi, some recipes in the introduction section. e.g. _Knowledge graphs and FAIR_ and _FAIR and the notion of metadata_, don't have a persistent FCB0XX ID.  Is it possible to generate IDs for such recipes? Thanks!

**Comment by proccaserra** [comment]
@FuqiX they do indeed. Would you like to review them before we mint?

**Comment by proccaserra** [comment]
https://w3id.org/faircookbook/FCB068
https://w3id.org/faircookbook/FCB069
https://w3id.org/faircookbook/FCB070
https://w3id.org/faircookbook/FCB071
