### ISSUE TITLE
Broken links in page footer

### ISSUE THREAD

**Issue by daniwelter** [FAIRplus/the-fair-cookbook#453]
Some of the links and icons in the Cookbook footer are broken, most notably the "Contributors" link, which goes to a 404 page.

![Screenshot 2022-06-15 at 14 23 07](https://user-images.githubusercontent.com/1267974/173825972-402acc6f-e74c-44b0-8a71-99a6d5cdbe08.png)

**Comment by proccaserra** [comment]
@terazus 

- [x] new redesign fixes broken image links
- [ ] fix `Contributors` link: 

> replace `https://faircookbook.elixir-europe.org/content/recipes/boilerplate/people.html/`
> with `https://faircookbook.elixir-europe.org/content/recipes/afterword/people.html`
