### ISSUE TITLE
Links, typo and suggestion on Findability: Search Engine Optimisation page

### ISSUE THREAD

**Issue by ljgarcia** [FAIRplus/the-fair-cookbook#48]
**Describe the bug**
1. The second image is not properly rendered. What I see now is a link to https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtIVE1MIHBhZ2VdIC0tPnwgU2VhcmNoIEVuZ2luZSBPcHRpbWl6YXRpb258IEIoZmE6ZmEtc2VhcmNoIFNjaGVtYS5vcmcgYXVnbWVudGVkIEhUTUwgcGFnZSlcbiAgQiAtLT4gQ3t3aGljaCB0ZWNobmlxdWU_fVxuICBDIC0tPnxPbmV8IERbZmE6ZmEtc3RhciBmYTpmYS1zdGFyIGZhOmZhLXN0YXIgSlNPTi1MRF1cbiAgQyAtLT58VHdvfCBFW2ZhOmZhLXN0YXIgZmE6ZmEtc3RhciBSREZhXVxuICBDIC0tPnxUaHJlZXwgRltmYTpmYS1zdGFyIG1pY3JvZm9ybWF0XVxuICBEIC0tPiBHXG5cdEUgLS0-IEdcbiAgRlx0LS0-IEdbZmE6ZmEtc2VhcmNoIGZhOmZhLWNvZyBmYTpmYS1maWdodGVyLWpldCBpbXByb3ZlZCBkaXNjb3ZlcmFiaWxpdHldIiwibWVybWFpZCI6eyJ0aGVtZSI6Im5ldXRyYWwifX0
2. Bioschemas is misspelled on the subtitle "Bioschema: trying to address the coverage gap"

**To Reproduce**
1. Go to https://github.com/FAIRplus/the-fair-cookbook/blob/bioschemas-seo/docs/content/recipes/infrastructure/seo.md
2. Scroll down to the link right after the first image depicting the recipe objectives
3. See a link rather than an image displayed.
4. Now go to the subtitle "Bioschema: trying to address the coverage gap", it should be Bioschemas

**Expected behavior**
1. I expect to see the image rather than the link
2. I expect to see Bioschemas rather than Bioschema (missing 's' at the end)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 75.0

**Additional context**
I suggest mentioning Bioschemas on the main objective together with schema.org as Bioschemas types are used in the recipe objectives graphic.
Page created by @AlasdairGray

**Comment by AlasdairGray** [comment]
Thanks for the feedback @ljgarcia
