### ISSUE TITLE
Markup error on page Findability: Datacatalog markup

### ISSUE THREAD

**Issue by ljgarcia** [FAIRplus/the-fair-cookbook#49]
**Describe the bug**
It looks like the code block was not properly used on Step 6. Make adjustments for any bits that could not be properly entered through the form.

**To Reproduce**
1. Go to https://github.com/FAIRplus/the-fair-cookbook/blob/bioschemas-seo/docs/content/recipes/infrastructure/bioschemas-datacatalog.md
2. Scroll down to Step 6. Make adjustments for any bits that could not be properly entered through the form. under subtitle Method
"provider": { "@type": "Organization", "@id": "https://fairsharing.org/communities" } ],
rendered as regular text rather than code and then step 7 rendered as code rather than text

**Expected behavior**
I expect to see a code rendered as code
```
"provider": { "@type": "Organization", "@id": "https://fairsharing.org/communities" } ],
```
and then text, tables and so normally rendered, not as code as it happens now.

**Screenshots**
![image](https://user-images.githubusercontent.com/5427252/80701345-8613b500-8adf-11ea-8ecd-5a0f48d04133.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 75.0

**Additional context**
Page contributed by @AlasdairGray

**Comment by AlasdairGray** [comment]
Thanks @ljgarcia
