### ISSUE TITLE
Update recipe name of geno data submission recipe

### ISSUE THREAD

**Issue by erlefloch** [FAIRplus/the-fair-cookbook#525]
The page is named "miappe" which is a metadata standard for plant **phenotyping** experiments. The logic behind was probably insisting on interoperability between genomic and phenotyping data. We think that beyond the community who developed the recipe, this naming can be confusing. Besides, it creates a problem if we want to develop a recipe dedicated to phenomics.
@cpommier @sebeier what do you think about it ?
AFAB and Erwan

**Comment by erlefloch** [comment]
@FuqiX is there a way to rename the page ? The idea would be to have two distinct pages (one for geno data submission and one for pheno data submission) with more precise names

**Comment by cpommier** [comment]
Hi, 
we definitly need to rename that page to `plant_geno_omic_embl-ebi`
The new MIAPPE phenomics page can be named : `plant_pheno_dataverse_edale`or `plant_pheno_dataverse_edale_miappe`

**Comment by cpommier** [comment]
Would that be ok for you @FuqiX ?

**Comment by erlefloch** [comment]
Let's use `plant_pheno_data_publication` and `plant_geno_data_publication` .

**Comment by proccaserra** [comment]
@cpommier @erlefloch 
2 quick things :

1. we can change the name of the markdown file but i'll need also to amend the .htaccess file on w3id to ensure the w3id properly redirects.
2. PR#595: the suggestion is to change to "MIAPPE-compliant plant genomics data submission to EMBL-EBI databases".
we can change the main title of the recipe but the recipe name showing up in the card is also used for building the table of content and here we use a convention to keep things short and consistent looking.
Additionally, as we have included this recipe to show case a shift in maturity level, it would make sense to keep the 'recipe name' (not the title, which can be what you suggest).

Would that work for you?

**Comment by erlefloch** [comment]
PR #603

**Comment by erlefloch** [comment]
geno recipe name was updated in https://github.com/FAIRplus/the-fair-cookbook/pull/606
