### ISSUE TITLE
Addition of ND4BB workflow on Knime Hub

### ISSUE THREAD

**Issue by YojanaGadiya** [FAIRplus/the-fair-cookbook#574]
@proccaserra I have now added the ND4BB Knime workflows on KNIME Hub. Please let me know if you would like me to open a PR with the changes in the respective recipe.

KNIME Hub- https://hub.knime.com/-/spaces/-/latest/~kWtm8A9mkrfEaN5R/

**Comment by proccaserra** [comment]
Hi Yojana,

yes please do

P
