### ISSUE TITLE
Issue on page /content/recipes/interoperability/c4c-clinical-trials.html

### ISSUE THREAD

**Issue by ronaldcornet** [FAIRplus/the-fair-cookbook#611]
Github handles are not correctly rendered. NB: this seems to be a generic issue, not a page-specific one.

**Comment by proccaserra** [comment]
@ronaldcornet 
thank you for reporting, we'll need to add the github handles for the new authors to the global_variables_fairplus.py
the github handles are properly rendered if provided.
addiing yours now, if you happen to have those for Avril, Becca and Anando, can fix this in a cinch

**Comment by ronaldcornet** [comment]
Hi @proccaserra ,
On Edge, I see as handle for you as well as Danielle: https://github.com/%7Bgithub_handle%7D
So it seems the replacement isn't adequately implemented. 
I had edited / pulled the github handle: @ronaldcornet and my NL affiliation with Elixir, not sure if I did that correctly, though.

Thanks for fixing it!
