### ISSUE TITLE
Survey of Identification schemas and infrastructure among FAIRplus partners

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#65]
**Is your feature request related to a problem? Please describe.**

Obtain information about how common the practice described in "https://fairtoolkit.pistoiaalliance.org/use-cases/adoption-and-impact-of-an-identifier-policy-astrazeneca/" actually is among Pharma/EFPIA partners

**Describe the solution you'd like**

based on the Pistoia Alliance document https://fairtoolkit.pistoiaalliance.org/use-cases/adoption-and-impact-of-an-identifier-policy-astrazeneca/, create a survey of what is used by EFPIA partners and contrast with infrastructure relied upon in open source projects.

pinging @robertgiessmann @karsten-quast @ereynrs @nsjuty (but not limited to) for initial discussion

**Comment by robertgiessmann** [comment]
did any discussion happen on this? can we close this because of low priorisation as of right now?

**Comment by AlasdairGray** [comment]
Are low priority issues that are closed being kept track of somewhere else?

**Comment by robertgiessmann** [comment]
not really, they are just moved to "Closed" issue. You are very right in raising this problem, though. I created a "backlog" label for this, so we can find "closed" issues (because of low priority / resource constraints) more easily.
