### ISSUE TITLE
Add a section for tools for FAIRification

### ISSUE THREAD

**Issue by sgtp** [FAIRplus/the-fair-cookbook#70]
**Is your feature request related to a problem? Please describe.**
We are missing an overview of what tools are available on the market or as OS to perform some FAIRification steps.

**Describe the solution you'd like**
We can just have a section for that, kept dynamic and we can invite contributions for interested parties (tools developers). We will need to add a review process from FAIRplus.

**Describe alternatives you've considered**
Go to other resources (FAIR matrix? Pistoia? bu there is nothing comprehensive enough and FAIRplus is in a good spot to try to be a reference.

**Additional context**
It's difficult, as being up2data and reasonably complete is hard. But as this is an open document, it may work. If it works, this would be very useful.

**Comment by proccaserra** [comment]
@sgtp now creating a dedicated page for this as a stop gap measure.

TODO: evaluate how to collect all the tools listed in each. of the recipes.  @fuqi @daniwelter you may be already doing this.
