### ISSUE TITLE
Identifier Resolution Service

### ISSUE THREAD

**Issue by AlasdairGray** [FAIRplus/the-fair-cookbook#72]
Stub recipe exists at https://github.com/FAIRplus/the-fair-cookbook/blob/identifiers/docs/content/recipes/findability/identifier-services/id-resolution.md

This recipe should cover the use of Identifiers.org. In particular how to register your data source with the service.

**Comment by AlasdairGray** [comment]
Recipe now moved to separate [branch](https://github.com/FAIRplus/the-fair-cookbook/tree/id-resolution-services). Mentioned in PR #157

**Comment by YojanaGadiya** [comment]
@AlasdairGray this issue is resolved it looks. Can I close the issue?

**Comment by AlasdairGray** [comment]
Yes, I think we can
