### ISSUE TITLE
recipe writing for UC30.recipe2 (FASTQ validator)

### ISSUE THREAD

**Issue by robertgiessmann** [FAIRplus/the-fair-cookbook#75]
Hi Philippe and extended editorial board,

here comes the abstract for UC30.recipe2 on how to check FASTQ files for conformance with a specific interpretation of the FASTQ specification:

[**Recipe: how to validate a FASTQ file**](https://github.com/FAIRplus/the-fair-cookbook/blob/uc30/docs/content/recipes/interoperability/how-to-validate-a-fastq-file.md)

The FASTQ format is a popular format for storing sequences (i.e. letters representing nucleotides in a piece of DNA) and their corresponding quality scores. However, FASTQ files can exhibit a large variety of variants=dialects, and might get corrupted during file transfers. It is thus important to check the conformance of a given FASTQ file to a specific expectation of "how it should look like", e.g. to ensure compatibility with a given tool. This recipe will outline how a FASTQ file can be checked locally, i.e. without transferring it out of the borders of a certain local computer environment.  

---- To anticipate the exact scope of "certain local computer environments": Linux machine (assuming Debian, but probably extendable to other distros), Python3 and pip3 already installed, no root access.

You find the link to the recipe here: https://github.com/FAIRplus/the-fair-cookbook/blob/uc30/docs/content/recipes/interoperability/how-to-validate-a-fastq-file.md

Dear Philippe and others, do you have feedback on this abstract?

Thanks,
   Robert

**Comment by robertgiessmann** [comment]
Things to do:

[x] write abstract
[ ] get feedback on abstract = scoping
[ ] write recipe, version 0.1
[ ] send out to interested reviewers
[ ] discuss recipe in its current state at squad call on 2020-06-24

**Comment by robertgiessmann** [comment]
fyi: I believe that the definition of http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_3914#classPermalinkModal is wrong, it just looks like the definition of http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_2531#classPermalinkModal ...

**Comment by robertgiessmann** [comment]
it might be interesting to add a child to http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_2337  regarding adherence to standard / spec of a specific file, e.g. called "File metadata"

**Comment by robertgiessmann** [comment]
tt:
  - 20 min: research on the correct  terms from EDAM ontology, recipe skeleton, minimal mermaid

**Comment by robertgiessmann** [comment]
tt:
- 10 min: getting the requirements and corresponding tests right

**Comment by robertgiessmann** [comment]
tt:
  - wasted 15 minutes, because BioPython is not able to check the fastq file properly. Dumb thing. Also, I already started to write some recipe instructions for that, so I can scrap that. Should better read and follow my own todo list above.

**Comment by robertgiessmann** [comment]
tt:
- 25min: no other solution found that would fulfill the requirement. Going with Biopython nevertheless, reducing the scope of recipe.

**Comment by robertgiessmann** [comment]
have to stop for now because I will be in a call.

**Comment by proccaserra** [comment]
I have used this to test files https://pypi.org/project/pyfastx/

**Comment by robertgiessmann** [comment]
tt:
- 10 min: finished the code

**Comment by robertgiessmann** [comment]
tt:
- 30 min: finished the recipe

**Comment by robertgiessmann** [comment]
link to the recipe: https://github.com/FAIRplus/the-fair-cookbook/blob/uc30/docs/content/recipes/interoperability/how-to-validate-a-fastq-file.md
