### ISSUE TITLE
Search function doesn't work in cookbook dev

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#76]
**Describe the bug**
The search function doesn't work in https://fairplus.github.io/cookbook-dev/search.html

Searching in Cookbook dev stucks at this page (see image below). It should return the search results.

**Screenshots**
<img width="583" alt="Capture" src="https://user-images.githubusercontent.com/54043294/85292670-2bba2380-b494-11ea-815a-be87d944959e.PNG">

**Comment by robertgiessmann** [comment]
deemed not time-critical, as this is the dev version

**Comment by proccaserra** [comment]
fixed in the current version.

relates to issue #437
