### ISSUE TITLE
OncoTrack, ND4BB, RESOLUTE recipe generalization

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#8]
Some ideas on recipes that can be generated from the raw recipes:
1) where to submit my data, a recommendation of hosting platform depending on datasets
2) how to perform ontology annotation
3) how to build an ETL
4) what is the community standards for different data types (Minimum information standard)
5) How to build a pipeline (Using KNIME to build reusable workflow) @Manfred might be more experienced in this work

**Comment by proccaserra** [comment]
@FuqiX (@vioannid @mkoatwork ) Is the idea to create individual recipe for each of those tasks as generically as possible and then reorganise the 4 initial examples as application and combination of these fundamental recipes?

if so, let me know so we can revisit the people assigned to the tasks identified in our table of content (Section 3.3.1.3 Vocabulary mapping,  Section 3.3.2.1 ETL, as well as Section 3.4.3 Providing enough metadata descriptors.

cheers

**Comment by FuqiX** [comment]
@proccaserra Yes! Although the four raw recipes are over-fitted to those datasets. There are still a lot of general recipes can be extracted from those raw recipes. 

For example, 
RESOLUTE used the **FAIREvaluator (ToC:: R4.3.1)**, @JolandaS might know more about this section
OncoTrack used **open-source vocabulary and terminology service** (ToC::R3.3.1.4)
OncoTrack also touched some parts of the **ETL tools** (ToC::R3.3.2.1)

It would be great if we can make the most of those recipes.

**Comment by robertgiessmann** [comment]
can we close this issue? I don't see resources to work on this.

**Comment by mkoatwork** [comment]
Hi All,

Yes, we can close this issue, but should report to the management board that there are no resources available.

Best regards/Viele Grüße
Manfred

**Comment by robertgiessmann** [comment]
Hi @mkoatwork Manfred, thanks for your comment. Which persons are for you in the management board that I could bring this to? I would be happy to do so, but feel unable to decide whom to address.

**Comment by mkoatwork** [comment]
@robertgiessmann Hi Robert, at least WP5 (projekt management) should be informed as we have to deliver datasets from 20 different IMI projects as FAIRified as possible. Until now we only have data from ReSolute used to make it more FAIR. The WP leaders must decide on sufficient ressources for all the tasks.

**Comment by robertgiessmann** [comment]
I wrote this email:

> Dear project management, 
> 
> this email is to inform you that we have an outstanding issue on GitHub on the generalization of OncoTrack, ND4BB, and RESOLUTE “experience reports” in our cookbook. 
> 
> The corresponding issue is: https://github.com/FAIRplus/the-fair-cookbook/issues/8
> 
> We (PM and myself) already had a chat regarding commitment, but this is probably an even more general resourcing question. Noone is truly responsible “to make the most of the produced recipes”, so I don’t know where to get the resources from either.
> 
> Please let me know whether you want to discuss this in any setting.
> 
> Best,
>    Robert
>
