### ISSUE TITLE
UC30R2 FASTQ validator for file submission

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#84]
FASTQ file validation solutions. Available validators, how to select and how to use.

WIP: see recipe draft here. https://github.com/FAIRplus/the-fair-cookbook/blob/UC30R2_FASTQ-validator_in_archives/docs/content/recipes/interoperability/fastq-file-format-validators.md

**Comment by robertgiessmann** [comment]
Hi Fuqi, could you please provide an abstract for your recipe here in this tracker? Please aim for 50 to 150 words.

**Comment by FuqiX** [comment]
> Hi Fuqi, could you please provide an abstract for your recipe here in this tracker? Please aim for 50 to 150 words.

please find the details in the link above

**Comment by robertgiessmann** [comment]
hi Fuqi, thanks for your quick reply. I couldn't find an abstract in the document you referenced -- can you help me to find it? Thanks, Robert

**Comment by FuqiX** [comment]
@EvaMart @proccaserra Hi, both. Thank you for volunteering to review the recipe. Please find the review form here https://forms.gle/x8T8DeJbNcen38BBA You are also welcomed to edit the recipe directly. :)
