### ISSUE TITLE
Extract 'Challenges in FAIR' from the EFPIA live requirements and interviews

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#9]
Identifying the competency questions and use cases has been an important part in our work.
Is it possible to have a chapter about the FAIR background and identify the key challenges in FAIR?
The interviews and EFPIA requirements can be helpful to extract such info.

**Comment by robertgiessmann** [comment]
hi @FuqiX , is this issue relevant anymore or can it be closed?

**Comment by FuqiX** [comment]
This ticket is about whether the EFPIA interview should be in the cookbook and how to present the interview outcome in cookbook. I am okay to close it since no one is working on this
