### ISSUE TITLE
New Recipe documenting how to convert from vendor specific format to an open standard: Mass Spec as an examplar

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/the-fair-cookbook#91]
Anchored in IMI Resolute projects (@ulo @sedlyarov ): targeted metabolite profiling -> raw data available from UL servers.

- show use of FAIRsharing to lookup open standards
- show use of proteowizard (via docker container) to produce mzML file
- show use of biotools to lookup libraries supporting the open specification
- show use of said library
- conclusion: lessons learned and navigation to other related recipes

**Comment by robertgiessmann** [comment]
Hi Philippe, I looked at:

https://github.com/FAIRplus/the-fair-cookbook/blob/3e2e6ee08239793e93551d16ed04acc6fa46d270/docs/content/recipes/interoperability/from-proprietary-to-open-standard-mzml-exemplar.md

That recipe looks to me like an "Epic" -- an end-to-end experience report (well, the title already warns it is "an exemplar"), which could be broken down further. I see at least

1) obtain a dataset via SFTP etc.
2) how to find a specification on fairsharing.org
3) convert Waters to mzML
4) validating mzML
5) how to find a tool on bio.tools
6) how to introspect mzML with pymzml

Could you elaborate -- when time permits -- why it is all in one recipe? Thanks!

**Comment by proccaserra** [comment]
thx @robertgiessmann great questions:, short answer = not to salami slice the recipe too much.
long answer: having all the key steps in one recipe provides more guidance. I already provision with placeholders for links to key recipes (e.g. how to package an archive more effectively with bdbags (which is a means to obtain checksums, create a manifest file and zipped a bag of digital files, There was also an intent to provide a more detailed recipe about using FAIRsharing -> can create an issue, good call). This is was also to provide a complement to the detailed approach being undertaken with FASTQ files, so in that example, the idea was to take reader from A to Z, from checking a catalogue of standards and making sure that the output of conversion is parseable.
ℹ️ currently writing a follow-up recipe showing how to bootstrap create of an ISA metadata file from a bag of mzml file
ℹ️ currently writing a follow-up recipe showing how to use the Biocrates XML file to create an ISA metadata file + validation etc.

TODO: add a mermaid diagram providing a visual overview to the recipe.
thx for the quick feedback

**Comment by robertgiessmann** [comment]
hi @proccaserra , I believe that we will need two kind of "article types" then: 1) salami-sliced recipes, and 2) pipeline-compilation examples. You also brought up even more "article types": 3) lessons learned / "demands to the public" / best-practice checklists.

It will need an extra call to discuss this, I believe.

**Comment by proccaserra** [comment]
https://w3id.org/faircookbook/FCB029
